---
sudo: required
language: python
python:
    - "3.6"
services:
    - postgresql
addons:
    postgresql: 9.6
before_script:
    - sudo apt-get -qq update
    - sudo apt-get install -qq postgresql-9.6-postgis-2.4
    - sudo apt-get install -qq python-gdal
    - export POSTGRES_USER="test"
    - psql -c "create database ${POSTGRES_USER}" -U postgres
    - psql -c "create extension postgis;" -U postgres
    - export DATABASE_URL="postgis://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER}"
install:
    - make
    - pipenv install coveralls --skip-lock
script:
    - make test
after_success:
    - coveralls

# sudo: required
# services:
#     - docker
# before_install:
#     - touch .env.local
# script:
#     - docker-compose -f dev.yml run app pytest --cov-report term --cov=v1
