language: python

python:
    - "3.6"

addons:
    postgresql: 9.6
    apt:
        update: true
        packages:
            - postgresql-9.6-postgis-2.3
            - libproj-dev
            - libgeos-dev

before_script:
    - export DB="baseproject"
    - export DATABASE_URL="postgis://postgres@localhost/${DB}"
    - psql -c "create database ${DB};" -U postgres
    - psql -c "create extension postgis;" -U postgres

install:
    - make

script:
    make test

after_success:
    coveralls

# language: python

# python:
#     - "3.6"

# dist: trusty
# sudo: required

# addons:
#     apt:
#         update: true
#     postgresql: "9.6"

# before_install:
#     - sudo apt-get update
#     - psql -U postgres -c "create extension postgis"
#     - sudo apt-get install -qq musl-dev postgresql-dev perl file libxml2-dev libgcc postgresql-client
#     - sudo apt-get install -qq jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev
#     - sudo apt-get install -qq libffi-dev py-cffi
#     - sudo apt-get install -qq gettext
#     - sudo apt-get install -qq gdal-dev geos

# install: make

# script: make test
