---
sudo: required
services:
    - docker
before_install:
    - touch .env.local
script:
    - docker-compose build
    - docker-compose -f dev.yml run app pytest --cov-report term --cov=v1
    - docker-compose -f dev.yml run app coveralls
