---
sudo: required
language: python
python:
    - "3.6"
services:
    - postgresql
addons:
    postgresql: 9.6
before_script:
    - sudo apt-get -qq update
    - sudo apt-get install -qq postgresql-9.6-postgis-2.4
    - sudo apt-get install -qq python-gdal
    - psql -c "create extension postgis;" -U postgres
    - psql -c "create database test;" -U postgres
    - export DATABASE_URL="postgis://postgres:@localhost:5432/test"
install:
    - make
    - pipenv install coveralls --skip-lock
script:
    - make test
after_success:
    - coveralls
